### ISSUE TITLE
how to create a directory?

### ISSUE THREAD

**Issue by AmbiBox** [jncronin/rpi-boot#12]
how to create a directory?

**Comment by scientistnik** [comment]
$ mkdir <name_dir>
no?

**Comment by AmbiBox** [comment]
FILE *f = fopen("mkdir", "w");
no ?

**Comment by jncronin** [comment]
The FAT and ext2 file systems in rpi-boot do not currently support writing to the file system.  This includes creating directories.  The underlying block devices do have write support, however.
