### ISSUE TITLE
rpi2 boots into hyp mode

### ISSUE THREAD

**Issue by eryjus** [jncronin/rpi-boot#23]
First, I have not confirmed that this is a genuine issue through debugging `rpi-boot`, but I have been fighting with this for some time on another project and want to raise this thought here.  When the rpi2 boots, it is likely to come up in hyp mode.  This changes the structure of several things including the location of the interrupt vector table.

This should be able to be disabled in the config.txt, but I was not successful in doing in my other tests -- and therefore had to write some code to 'thunk' the cpu into svc mode if it is in hyp mode.  At the same time, if we happen to be in some other mode, I change to svc mode as well.

I want to put this into my fork and push it back to you, but that will require me to update the '-mcpu' parameter for the compiler/assembler and that is likely to break the rpi build.

The code I am interested in adding is as follows (in boot.s and likely boot64.s), immediately after the Start label:

```
Start:
    mrs     r3,cpsr                     @@ get the current program status register
    and     r3,#0x1f                    @@ and mask out the mode bits
    cmp     r3,#0x1a                    @@ are we in hyp mode?
    beq     hyp                         @@ if we are in hyp mode, go to that section
    cpsid   iaf,#0x13                   @@ if not switch to svc mode, ensure we have a stack for the kernel; no ints
    b       cont                        @@ and then jump to set up the stack

@@ -- from here we are in hyp mode so we need to exception return to the svc mode
hyp:
    mrs     r3,cpsr                     @@ get the cpsr again
    and     r3,#~0x1f                   @@ clear the mode bits
    orr     r3,#0x013                   @@ set the mode for svc
    orr     r3,#1<<6|1<<7|1<<8          @@ disable interrupts as well
    msr     spsr_cxsf,r3                @@ and save that in the spsr

    ldr     r3,=cont                    @@ get the address where we continue
    msr     elr_hyp,r3                  @@ store that in the elr register

    eret                                @@ this is an exception return

@@ -- everyone continues from here
cont:
```

This code is tested on real rpi2 hardware.  However, the `elr_hyp` special register is not available on the arm1176jzf-s cpu (requires -mcortex-a7).  I guess it could be bit-coded if need be; it theoretically would never be executed on an rpi since it does not have that mode....

Anyway, I wanted to open this issue for conversation.  Please let me know your thoughts on this.

**Comment by jncronin** [comment]
Thanks for this.  I have investigated omitting the mcpu option completely in the boot.s compilation line and things seem to compile cleanly and it works on qemu's raspi2 implementation.  I will investigate further with a real rpi v1 and add it to the repository if it works.

**Comment by jncronin** [comment]
I can confirm this is fine for v1 pi, therefore committed to repository.  Thanks again.
